#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Nov 08, 2021 07:41:20 PM EET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Geeks_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Geeks_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Geeks_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+383+106")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.05, rely=0.089, relheight=0.696
                , relwidth=0.838)
        self.Canvas1.configure(background="#0080ff")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="blue")
        self.Canvas1.configure(selectforeground="white")

        self.PCTECHGREU_The_GEKKS = tk.Text(self.Canvas1)
        self.PCTECHGREU_The_GEKKS.place(relx=0.159, rely=0.447, relheight=0.204
                , relwidth=0.445)
        self.PCTECHGREU_The_GEKKS.configure(background="white")
        self.PCTECHGREU_The_GEKKS.configure(font="TkTextFont")
        self.PCTECHGREU_The_GEKKS.configure(foreground="black")
        self.PCTECHGREU_The_GEKKS.configure(highlightbackground="#d9d9d9")
        self.PCTECHGREU_The_GEKKS.configure(highlightcolor="black")
        self.PCTECHGREU_The_GEKKS.configure(insertbackground="black")
        self.PCTECHGREU_The_GEKKS.configure(selectbackground="blue")
        self.PCTECHGREU_The_GEKKS.configure(selectforeground="white")
        self.PCTECHGREU_The_GEKKS.configure(wrap="word")

        self.Bee_Geekk = tk.Message(self.Canvas1)
        self.Bee_Geekk.place(relx=0.258, rely=0.192, relheight=0.073
                , relwidth=0.119)
        self.Bee_Geekk.configure(background="#d9d9d9")
        self.Bee_Geekk.configure(foreground="#000000")
        self.Bee_Geekk.configure(highlightbackground="#d9d9d9")
        self.Bee_Geekk.configure(highlightcolor="black")
        self.Bee_Geekk.configure(text='''Message''')
        self.Bee_Geekk.configure(width=60)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





