#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 20, 2021 07:37:11 PM EEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Github_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Github_support.set_Tk_var()
    top = Toplevel1 (root)
    Github_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Github_support.set_Tk_var()
    top = Toplevel1 (w)
    Github_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+383+106")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.github.com = tk.Button(top)
        self.github.com.place(relx=0.317, rely=0.8, height=54, width=167)
        self.github.com.configure(activebackground="#ececec")
        self.github.com.configure(activeforeground="#000000")
        self.github.com.configure(background="#d9d9d9")
        self.github.com.configure(disabledforeground="#a3a3a3")
        self.github.com.configure(foreground="#000000")
        self.github.com.configure(highlightbackground="#d9d9d9")
        self.github.com.configure(highlightcolor="black")
        self.github.com.configure(pady="0")
        self.github.com.configure(text='''Button''')

        self.OK_! = tk.Checkbutton(top)
        self.OK_!.place(relx=0.167, rely=0.667, relheight=0.056, relwidth=0.102)
        self.OK_!.configure(activebackground="#ececec")
        self.OK_!.configure(activeforeground="#000000")
        self.OK_!.configure(background="#d9d9d9")
        self.OK_!.configure(disabledforeground="#a3a3a3")
        self.OK_!.configure(foreground="#000000")
        self.OK_!.configure(highlightbackground="#d9d9d9")
        self.OK_!.configure(highlightcolor="black")
        self.OK_!.configure(justify='left')
        self.OK_!.configure(text='''Check''')
        self.OK_!.configure(variable=Github_support.che46)

        self.github.com_Lets_Code_! = tk.Message(top)
        self.github.com_Lets_Code_!.place(relx=0.15, rely=0.156, relheight=0.251
                , relwidth=0.417)
        self.github.com_Lets_Code_!.configure(background="#d9d9d9")
        self.github.com_Lets_Code_!.configure(foreground="#000000")
        self.github.com_Lets_Code_!.configure(highlightbackground="#d9d9d9")
        self.github.com_Lets_Code_!.configure(highlightcolor="black")
        self.github.com_Lets_Code_!.configure(text='''Message''')
        self.github.com_Lets_Code_!.configure(width=250)

if __name__ == '__main__':
    vp_start_gui()





