Get-NetTCPSetting
   [[-SettingName] <String[]>]
   [-MinRtoMs <UInt32[]>]
   [-InitialCongestionWindowMss <UInt32[]>]
   [-CongestionProvider <CongestionProvider[]>]
   [-CwndRestart <CwndRestart[]>]
   [-DelayedAckTimeoutMs <UInt32[]>]
   [-DelayedAckFrequency <Byte[]>]
   [-MemoryPressureProtection <MemoryPressureProtection[]>]
   [-AutoTuningLevelLocal <AutoTuningLevelLocal[]>]
   [-AutoTuningLevelGroupPolicy <AutoTuningLevelGroupPolicy[]>]
   [-AutoTuningLevelEffective <AutoTuningLevelEffective[]>]
   [-EcnCapability <EcnCapability[]>]
   [-Timestamps <Timestamps[]>]
   [-InitialRtoMs <UInt32[]>]
   [-ScalingHeuristics <ScalingHeuristics[]>]
   [-DynamicPortRangeStartPort <UInt16[]>]
   [-DynamicPortRangeNumberOfPorts <UInt16[]>]
   [-AutomaticUseCustom <AutomaticUseCustom[]>]
   [-NonSackRttResiliency <NonSackRttResiliency[]>]
   [-ForceWS <ForceWS[]>]
   [-MaxSynRetransmissions <Byte[]>]
   [-AutoReusePortRangeStartPort <UInt16[]>]
   [-AutoReusePortRangeNumberOfPorts <UInt16[]>]
   [-AssociatedTransportFilter <CimInstance>]
   [-CimSession <CimSession[]>]
   [-ThrottleLimit <Int32>]
   [-AsJob]
   [<CommonParameters>]