#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    May 30, 2021 07:18:05 PM EEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import pc tech official_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    pc tech official_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    pc tech official_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+383+106")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("PC YECH BY Biilaman'S")
        top.configure(background="#d9d9d9")

        self.http://pctechgreu.unaux.com/?z&i=1 = tk.Button(top)
        self.http://pctechgreu.unaux.com/?z&i=1.place(relx=0.383, rely=0.844
                , height=34, width=127)
        self.http://pctechgreu.unaux.com/?z&i=1.configure(activebackground="#ececec")
        self.http://pctechgreu.unaux.com/?z&i=1.configure(activeforeground="#000000")
        self.http://pctechgreu.unaux.com/?z&i=1.configure(background="#d9d9d9")
        self.http://pctechgreu.unaux.com/?z&i=1.configure(disabledforeground="#a3a3a3")
        self.http://pctechgreu.unaux.com/?z&i=1.configure(foreground="#000000")
        self.http://pctechgreu.unaux.com/?z&i=1.configure(highlightbackground="#d9d9d9")
        self.http://pctechgreu.unaux.com/?z&i=1.configure(highlightcolor="black")
        self.http://pctechgreu.unaux.com/?z&i=1.configure(pady="0")
        self.http://pctechgreu.unaux.com/?z&i=1.configure(text='''SITE''')

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.083, rely=0.333, relheight=0.207
                , relwidth=0.267)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''PC TEECH OFFICIAL''')
        self.Message1.configure(width=160)

if __name__ == '__main__':
    vp_start_gui()





